name: Golang tests

on:
  - push
  - pull_request

jobs:
  go-test:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.1

      - name: Setting up test dependencies
        run: .github/workflows/setup-test-dependencies.sh

      - name: Running Golang tests
        run: make test-go
